on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run_tests:
    name: "tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Sets up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' 

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint script
      - name: Lint
        run: npm run lint

      # Run test script
      # - name: Test
      #   run: npm run test

      # Run format script
      - name: Format
        run: npm run format

      # Run the type checker
      - name: Type check
        run: npm run typecheck